In [1]:
import pandas as pd

In [2]:
stats = pd.read_csv("stats.csv")

In [3]:
stats

,Unnamed: 0,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,TOTAL_AST,TOTAL_STL,TOTAL_BLK,TOTAL_TOV,TOTAL_PF,TOTAL_PTS,min_age,TOTAL_seasons,season_index,min_proportion
0,0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,...,71,59,23,99,117,750,27,11,0,0.659756
1,1,Byron Scott,SG,29,LAL,82,82,32.1,6.1,12.8,...,177,95,21,85,146,1191,29,7,0,0.801829
2,2,Elden Campbell,PF,22,LAL,52,0,7.3,1.1,2.4,...,10,11,38,16,71,144,22,15,0,0.182692
3,3,Irving Thomas,PF,25,LAL,26,0,4.2,0.7,1.9,...,10,4,1,13,24,46,25,1,0,0.103846
4,4,James Worthy,SF,29,LAL,78,74,38.6,9.2,18.7,...,275,104,35,127,117,1670,29,4,0,0.964103
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14087,14087,Spencer Hawes,PF,28,MIL,54,1,14.8,2.5,5.1,...,81,15,30,49,77,337,19,10,9,0.368981
14088,14088,Steve Novak,PF,33,MIL,8,0,2.8,0.3,0.9,...,0,0,0,0,1,5,23,11,10,0.068750
14089,14089,Terrence Jones,PF,25,MIL,54,12,23.5,4.3,9.1,...,59,40,54,48,67,584,21,6,4,0.587963
14090,14090,Thon Maker,C,19,MIL,57,34,9.9,1.5,3.2,...,23,10,26,17,84,226,19,5,0,0.246491
14091,14091,Tony Snell,SG,25,MIL,80,80,29.2,3.1,6.8,...,96,55,14,55,125,683,22,8,3,0.730000

In [4]:
stats.dtypes

Unnamed: 0          int64
Player             object
Pos                object
Age                 int64
Tm                 object
                   ...
TOTAL_PTS           int64
min_age             int64
TOTAL_seasons       int64
season_index        int64
min_proportion    float64
Length: 103, dtype: object

In [5]:
pd.isnull(stats).sum()

Unnamed: 0        0
Player            0
Pos               0
Age               0
Tm                0
                 ..
TOTAL_PTS         0
min_age           0
TOTAL_seasons     0
season_index      0
min_proportion    0
Length: 103, dtype: int64

In [6]:
pd.isnull(stats).sum().head(50)

Unnamed: 0        0
Player            0
Pos               0
Age               0
Tm                0
G                 0
GS                0
MP                0
FG                0
FGA               0
FG%              50
3P                0
3PA               0
3P%            2042
2P                0
2PA               0
2P%              84
eFG%             50
FT                0
FTA               0
FT%             462
ORB               0
DRB               0
TRB               0
AST               0
STL               0
BLK               0
TOV               0
PF                0
PTS               0
Year              0
Pts Won           0
Pts Max           0
Share             0
Team              0
W                 0
L                 0
W/L%              0
GB                0
PS/G              0
PA/G              0
SRS               0
FG_per_100        3
FGA_per_100       3
3P_per_100        3
3PA_per_100       3
2P_per_100        3
2PA_per_100       3
FT_per_100        3
FTA_per_100       3
dtype: int64

In [7]:
stats[pd.isnull(stats["ORtg"])][["Player", "FGA","MP","Year"]].head()

                   Player  FGA   MP  Year
103       Adrian Caldwell  0.0  3.0  1998
428            Gani Lawal  0.0  2.0  2011
2776  Trey McKinney-Jones  0.0  1.0  2018
3172           Andy Panko  0.0  1.0  2001
3894          Alex Scales  0.0  0.0  2006

In [8]:
pd.isnull(stats).sum().tail(31)

USG%              3
OWS               0
DWS               0
WS                0
WS/48             3
OBPM              0
DBPM              0
BPM               0
VORP              0
TOTAL_MP          0
TOTAL_FG          0
TOTAL_FGA         0
TOTAL_3P          0
TOTAL_3PA         0
TOTAL_2P          0
TOTAL_2PA         0
TOTAL_FT          0
TOTAL_FTA         0
TOTAL_ORB         0
TOTAL_DRB         0
TOTAL_TRB         0
TOTAL_AST         0
TOTAL_STL         0
TOTAL_BLK         0
TOTAL_TOV         0
TOTAL_PF          0
TOTAL_PTS         0
min_age           0
TOTAL_seasons     0
season_index      0
min_proportion    0
dtype: int64

In [9]:
stats = stats.fillna(0)

In [10]:
pd.isnull(stats).sum().tail(31)

USG%              0
OWS               0
DWS               0
WS                0
WS/48             0
OBPM              0
DBPM              0
BPM               0
VORP              0
TOTAL_MP          0
TOTAL_FG          0
TOTAL_FGA         0
TOTAL_3P          0
TOTAL_3PA         0
TOTAL_2P          0
TOTAL_2PA         0
TOTAL_FT          0
TOTAL_FTA         0
TOTAL_ORB         0
TOTAL_DRB         0
TOTAL_TRB         0
TOTAL_AST         0
TOTAL_STL         0
TOTAL_BLK         0
TOTAL_TOV         0
TOTAL_PF          0
TOTAL_PTS         0
min_age           0
TOTAL_seasons     0
season_index      0
min_proportion    0
dtype: int64

In [11]:
stats.groupby(["Player"]).get_group(("Greg Anderson"))

,Unnamed: 0,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,TOTAL_AST,TOTAL_STL,TOTAL_BLK,TOTAL_TOV,TOTAL_PF,TOTAL_PTS,min_age,TOTAL_seasons,season_index,min_proportion
3139,3139,Greg Anderson,C,33,ATL,50,0,8.0,0.7,1.6,...,15,19,10,17,85,88,26,7,6,0.199000
4194,4194,Greg Anderson,PF,29,DET,77,47,21.1,2.6,4.8,...,51,55,68,94,234,491,26,7,2,0.527273
7053,7053,Greg Anderson,PF,30,ATL,51,0,12.2,1.1,2.0,...,17,23,32,32,103,148,26,7,3,0.304902
7856,7856,Greg Anderson,PF,26,DEN,68,2,13.6,1.7,4.0,...,16,35,45,84,140,292,26,7,0,0.339706
7871,7871,Greg Anderson,PF,27,DEN,82,82,34.1,4.7,10.4,...,78,88,65,201,263,945,26,7,1,0.851524
9833,9833,Greg Anderson,PF,31,SAS,46,7,7.5,0.5,1.0,...,10,9,24,22,66,54,26,7,4,0.186957
9846,9846,Greg Anderson,C,32,SAS,82,48,20.2,1.6,3.2,...,34,63,67,73,225,322,26,7,5,0.505793

In [12]:

stats.dropna(subset=['TOTAL_MP'], inplace = True)
stats = stats[stats['TOTAL_MP'] >= 400]

In [13]:
stats

,Unnamed: 0,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,TOTAL_AST,TOTAL_STL,TOTAL_BLK,TOTAL_TOV,TOTAL_PF,TOTAL_PTS,min_age,TOTAL_seasons,season_index,min_proportion
0,0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,...,71,59,23,99,117,750,27,11,0,0.659756
1,1,Byron Scott,SG,29,LAL,82,82,32.1,6.1,12.8,...,177,95,21,85,146,1191,29,7,0,0.801829
4,4,James Worthy,SF,29,LAL,78,74,38.6,9.2,18.7,...,275,104,35,127,117,1670,29,4,0,0.964103
5,5,Larry Drew,PG,32,LAL,48,2,10.3,1.1,2.6,...,118,15,1,49,40,139,32,1,0,0.258333
6,6,Magic Johnson,PG,31,LAL,79,79,37.1,5.9,12.4,...,989,102,17,314,150,1531,31,2,0,0.928165
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14086,14086,Rashad Vaughn,SG,20,MIL,41,2,11.2,1.4,3.8,...,23,19,10,14,32,142,19,3,1,0.279268
14087,14087,Spencer Hawes,PF,28,MIL,54,1,14.8,2.5,5.1,...,81,15,30,49,77,337,19,10,9,0.368981
14089,14089,Terrence Jones,PF,25,MIL,54,12,23.5,4.3,9.1,...,59,40,54,48,67,584,21,6,4,0.587963
14090,14090,Thon Maker,C,19,MIL,57,34,9.9,1.5,3.2,...,23,10,26,17,84,226,19,5,0,0.246491
14091,14091,Tony Snell,SG,25,MIL,80,80,29.2,3.1,6.8,...,96,55,14,55,125,683,22,8,3,0.730000