In [53]:
import requests
import os
import shutil
import pandas as pd
from bs4 import BeautifulSoup
import os
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time

In [54]:
years = list(range(1991,2022))

In [55]:
url_start = "https://www.basketball-reference.com/awards/awards_{}.html"

for year in years:
    url = url_start.format(year)
    
    data = requests.get(url)
    
    with open("mvp/{}.html".format(year), "w+", encoding="utf-8") as f:
        f.write(data.text)

In [56]:
with open("mvp/1991.html", encoding="utf-8") as f:
    page = f.read()
    
soup = BeautifulSoup(page, 'html.parser')
soup.find('tr', class_="over_header").decompose()

In [57]:
mvp_table = soup.find_all(id="mvp")[0]

In [58]:
mvp_1991 = pd.read_html(str(mvp_table))[0]

In [59]:
mvp_1991.head(1)

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,PTS,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48
0,1,Michael Jordan,27,CHI,77.0,891.0,960,0.928,82,37.0,31.5,6.0,5.5,2.7,1.0,0.539,0.312,0.851,20.3,0.321

In [60]:
mvp_1991["Year"] = 1991

In [61]:
mvp_1991.head()

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,...,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48,Year
0,1,Michael Jordan,27,CHI,77.0,891.0,960,0.928,82,37.0,...,6.0,5.5,2.7,1.0,0.539,0.312,0.851,20.3,0.321,1991
1,2,Magic Johnson,31,LAL,10.0,497.0,960,0.518,79,37.1,...,7.0,12.5,1.3,0.2,0.477,0.320,0.906,15.4,0.251,1991
2,3,David Robinson,25,SAS,6.0,476.0,960,0.496,82,37.7,...,13.0,2.5,1.5,3.9,0.552,0.143,0.762,17.0,0.264,1991
3,4,Charles Barkley,27,PHI,2.0,222.0,960,0.231,67,37.3,...,10.1,4.2,1.6,0.5,0.570,0.284,0.722,13.4,0.258,1991
4,5,Karl Malone,27,UTA,0.0,142.0,960,0.148,82,40.3,...,11.8,3.3,1.1,1.0,0.527,0.286,0.770,15.5,0.225,1991

In [62]:
dfs = []
for year in years:
    with open("mvp/{}.html".format(year), encoding="utf-8") as f:
        page = f.read()
    
    soup = BeautifulSoup(page, 'html.parser')
    soup.find('tr', class_="over_header").decompose()
    mvp_table = soup.find_all(id="mvp")[0]
    mvp_df = pd.read_html(str(mvp_table))[0]
    mvp_df["Year"] = year
    dfs.append(mvp_df)

In [63]:
mvps = pd.concat(dfs)

mvps.tail()

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,...,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48,Year
10,11,Russell Westbrook,32,WAS,0.0,5.0,1010,0.005,65,36.4,...,11.5,11.7,1.4,0.4,0.439,0.315,0.656,3.7,0.075,2021
11,12,Ben Simmons,24,PHI,0.0,3.0,1010,0.003,58,32.4,...,7.2,6.9,1.6,0.6,0.557,0.300,0.613,6.0,0.153,2021
12,13T,James Harden,31,TOT,0.0,1.0,1010,0.001,44,36.6,...,7.9,10.8,1.2,0.8,0.466,0.362,0.861,7.0,0.208,2021
13,13T,LeBron James,36,LAL,0.0,1.0,1010,0.001,45,33.4,...,7.7,7.8,1.1,0.6,0.513,0.365,0.698,5.6,0.179,2021
14,13T,Kawhi Leonard,29,LAC,0.0,1.0,1010,0.001,52,34.1,...,6.5,5.2,1.6,0.4,0.512,0.398,0.885,8.8,0.238,2021

In [64]:
mvps.to_csv("mvps.csv")

In [20]:
player_stats_url = "https://www.basketball-reference.com/leagues/NBA_{}_per_game.html"

for year in years:
    url = player_stats_url.format(year)
    
    data = requests.get(url)
    
    with open("player/{}.html".format(year), "w+", encoding="utf-8") as f:
        f.write(data.text)

In [21]:
driver = webdriver.Chrome(executable_path=r"C:\Users\Cillian\chromedriver.exe")

C:\Users\Cillian\AppData\Local\Temp\ipykernel_15036\2556859761.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(executable_path=r"C:\Users\Cillian\chromedriver.exe")

In [22]:
for year in years:
    url = player_stats_url.format(year)
    
    driver.get(url)
    driver.execute_script("window.scrollTo(1,10000)")
    time.sleep(2)
    
    with open("player/{}.html".format(year), "w+", encoding="utf-8") as f:
        f.write(driver.page_source)

In [23]:
dfs = []
for year in years:
    with open("player/{}.html".format(year), encoding="utf-8") as f:
        page = f.read()
    
    soup = BeautifulSoup(page, 'html.parser')
    soup.find('tr', class_="thead").decompose()
    player_table = soup.find_all(id="per_game_stats")[0]
    player_df = pd.read_html(str(player_table))[0]
    player_df["Year"] = year
    dfs.append(player_df)

In [24]:
players = pd.concat(dfs)

In [25]:
players

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,1,Alaa Abdelnaby,PF,22,POR,43,0,6.7,1.3,2.7,...,0.6,1.4,2.1,0.3,0.1,0.3,0.5,0.9,3.1,1991
1,2,Mahmoud Abdul-Rauf,PG,21,DEN,67,19,22.5,6.2,15.1,...,0.5,1.3,1.8,3.1,0.8,0.1,1.6,2.2,14.1,1991
2,3,Mark Acres,C,28,ORL,68,0,19.3,1.6,3.1,...,2.1,3.2,5.3,0.4,0.4,0.4,0.6,3.2,4.2,1991
3,4,Michael Adams,PG,28,DEN,66,66,35.5,8.5,21.5,...,0.9,3.0,3.9,10.5,2.2,0.1,3.6,2.5,26.5,1991
4,5,Mark Aguirre,SF,31,DET,78,13,25.7,5.4,11.7,...,1.7,3.1,4.8,1.8,0.6,0.3,1.6,2.7,14.2,1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,536,Delon Wright,PG,28,SAC,27,8,25.8,3.9,8.3,...,1.0,2.9,3.9,3.6,1.6,0.4,1.3,1.1,10.0,2021
726,537,Thaddeus Young,PF,32,CHI,68,23,24.3,5.4,9.7,...,2.5,3.8,6.2,4.3,1.1,0.6,2.0,2.2,12.1,2021
727,538,Trae Young,PG,22,ATL,63,63,33.7,7.7,17.7,...,0.6,3.3,3.9,9.4,0.8,0.2,4.1,1.8,25.3,2021
728,539,Cody Zeller,C,28,CHO,48,21,20.9,3.8,6.8,...,2.5,4.4,6.8,1.8,0.6,0.4,1.1,2.5,9.4,2021
729,540,Ivica Zubac,C,23,LAC,72,33,22.3,3.6,5.5,...,2.6,4.6,7.2,1.3,0.3,0.9,1.1,2.6,9.0,2021

In [26]:
players.to_csv("players.csv")

In [2]:
import time
player_adv_stats_url = "https://www.basketball-reference.com/leagues/NBA_{}_advanced.html"

for year in years:
    url = player_adv_stats_url.format(year)
    
    data = requests.get(url)
    
    with open("player_adv/{}.html".format(year), "w+", encoding="utf-8") as f:
        f.write(data.text)

NameError: name 'years' is not defined

In [100]:
driver = webdriver.Chrome(executable_path=r"C:\Users\Cillian\chromedriver.exe")

C:\Users\Cillian\AppData\Local\Temp\ipykernel_9764\2556859761.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(executable_path=r"C:\Users\Cillian\chromedriver.exe")

In [101]:
for year in years:
    url = player_adv_stats_url.format(year)
    
    driver.get(url)
    driver.execute_script("window.scrollTo(1,10000)")
    time.sleep(2)
    
    with open("player_adv/{}.html".format(year), "w+", encoding="utf-8") as f:
        f.write(driver.page_source)

In [102]:
dfs = []
for year in years:
    with open("player_adv/{}.html".format(year), encoding="utf-8") as f:
        page = f.read()
    
    soup = BeautifulSoup(page, 'html.parser')
    soup.find('tr', class_="thead").decompose()
    player_adv_table = soup.find_all(id="advanced_stats")[0]
    player_adv_df = pd.read_html(str(player_adv_table))[0]
    player_adv_df["Year"] = year
    dfs.append(player_adv_df)

In [103]:
players_adv = pd.concat(dfs)

In [104]:
players_adv

,Rk,Player,Pos,Age,Tm,G,MP,PER,TS%,3PAr,...,OWS,DWS,WS,WS/48,Unnamed: 24,OBPM,DBPM,BPM,VORP,Year
0,1,Alaa Abdelnaby,PF,22,POR,43,290,13.1,.499,.000,...,0.0,0.5,0.5,.079,NaN,-3.4,-1.2,-4.6,-0.2,1991
1,2,Mahmoud Abdul-Rauf,PG,21,DEN,67,1505,12.2,.448,.099,...,-0.7,-0.3,-1.0,-0.031,NaN,-2.0,-3.0,-5.0,-1.1,1991
2,3,Mark Acres,C,28,ORL,68,1313,9.2,.551,.014,...,1.4,1.1,2.5,.090,NaN,-2.8,-0.2,-3.0,-0.3,1991
3,4,Michael Adams,PG,28,DEN,66,2346,22.3,.530,.397,...,5.8,0.4,6.3,.128,NaN,6.0,-0.7,5.3,4.3,1991
4,5,Mark Aguirre,SF,31,DET,78,2006,16.7,.526,.086,...,2.8,2.7,5.5,.132,NaN,1.2,0.2,1.4,1.7,1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,536,Delon Wright,PG,28,SAC,27,696,15.9,.563,.369,...,0.8,0.5,1.3,.092,NaN,0.5,0.6,1.2,0.6,2021
726,537,Thaddeus Young,PF,32,CHI,68,1652,20.3,.578,.068,...,2.8,2.2,5.1,.147,NaN,1.9,1.4,3.3,2.2,2021
727,538,Trae Young,PG,22,ATL,63,2125,23.0,.589,.357,...,5.9,1.3,7.2,.163,NaN,5.3,-1.7,3.7,3.0,2021
728,539,Cody Zeller,C,28,CHO,48,1005,18.2,.599,.086,...,2.1,1.1,3.3,.156,NaN,-0.2,-0.2,-0.5,0.4,2021
729,540,Ivica Zubac,C,23,LAC,72,1609,19.1,.693,.010,...,4.8,2.1,6.9,.206,NaN,0.6,0.4,1.0,1.2,2021

In [105]:
players_adv.to_csv("players_adv.csv")

In [4]:
import requests
import os
import shutil
import pandas as pd
from bs4 import BeautifulSoup
import os
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time

In [11]:
player_poss_stats_url = "https://www.basketball-reference.com/leagues/NBA_{}_per_poss.html"
years = list(range(1991,2022))

for year in years:
    url = player_poss_stats_url.format(year)
    
    data = requests.get(url)
    
    with open("player_poss/{}.html".format(year), "w+", encoding="utf-8") as f:
        f.write(data.text)

In [12]:
driver = webdriver.Chrome(executable_path=r"C:\Users\Cillian\chromedriver.exe")

C:\Users\Cillian\AppData\Local\Temp\ipykernel_15036\2556859761.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(executable_path=r"C:\Users\Cillian\chromedriver.exe")

In [13]:
for year in years:
    url = player_poss_stats_url.format(year)
    
    driver.get(url)
    driver.execute_script("window.scrollTo(1,10000)")
    time.sleep(2)
    
    with open("player_poss/{}.html".format(year), "w+", encoding="utf-8") as f:
        f.write(driver.page_source)

In [15]:
dfs = []
for year in years:
    with open("player_poss/{}.html".format(year), encoding="utf-8") as f:
        page = f.read()
    
    soup = BeautifulSoup(page, 'html.parser')
    soup.find('tr', class_="thead").decompose()
    player_poss_table = soup.find_all(id="per_poss_stats")[0]
    player_poss_df = pd.read_html(str(player_poss_table))[0]
    player_poss_df["Year"] = year
    dfs.append(player_poss_df)

In [16]:
players_poss = pd.concat(dfs)

In [18]:
players_poss

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,AST,STL,BLK,TOV,PF,PTS,Unnamed: 29,ORtg,DRtg,Year
0,1,Alaa Abdelnaby,PF,22,POR,43,0,290,9.1,19.1,...,2.0,0.7,2.0,3.6,6.4,22.2,NaN,99,103,1991
1,2,Mahmoud Abdul-Rauf,PG,21,DEN,67,19,1505,11.7,28.3,...,5.8,1.5,0.1,3.1,4.2,26.4,NaN,96,118,1991
2,3,Mark Acres,C,28,ORL,68,0,1313,4.0,7.9,...,0.9,0.9,0.9,1.5,8.0,10.5,NaN,116,109,1991
3,4,Michael Adams,PG,28,DEN,66,66,2346,10.1,25.6,...,12.5,2.6,0.1,4.3,2.9,31.5,NaN,113,115,1991
4,5,Mark Aguirre,SF,31,DET,78,13,2006,10.9,23.7,...,3.6,1.2,0.5,3.3,5.4,28.7,NaN,109,105,1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,536,Delon Wright,PG,28,SAC,27,8,696,7.2,15.5,...,6.7,3.0,0.8,2.4,2.1,18.7,NaN,115,115,2021
726,537,Thaddeus Young,PF,32,CHI,68,23,1652,10.9,19.4,...,8.5,2.2,1.2,4.0,4.5,24.2,NaN,116,110,2021
727,538,Trae Young,PG,22,ATL,63,63,2125,11.3,25.7,...,13.8,1.2,0.3,6.0,2.6,36.9,NaN,117,116,2021
728,539,Cody Zeller,C,28,CHO,48,21,1005,8.8,15.7,...,4.2,1.3,0.8,2.5,5.9,21.9,NaN,123,112,2021
729,540,Ivica Zubac,C,23,LAC,72,33,1609,7.9,12.1,...,2.8,0.7,1.9,2.5,5.8,20.0,NaN,135,110,2021

In [19]:
players_poss.to_csv("players_poss.csv")

In [27]:
team_stats_url = "https://www.basketball-reference.com/leagues/NBA_{}_standings.html"

In [30]:
for year in years:
    url = team_stats_url.format(year)
    
    data = requests.get(url)
    
    with open("team/{}.html".format(year), "w+", encoding="utf-8") as f:
        f.write(data.text)

In [31]:
dfs = []
for year in years:
    with open("team/{}.html".format(year), encoding="utf-8") as f:
        page = f.read()
    
    soup = BeautifulSoup(page, 'html.parser')
    soup.find('tr', class_="thead").decompose()
    e_table = soup.find_all(id="divs_standings_E")[0]
    e_df = pd.read_html(str(e_table))[0]
    e_df["Year"] = year
    e_df["Team"] = e_df["Eastern Conference"]
    del e_df["Eastern Conference"]
    dfs.append(e_df)
    
    w_table = soup.find_all(id="divs_standings_W")[0]
    w_df = pd.read_html(str(w_table))[0]
    w_df["Year"] = year
    w_df["Team"] = w_df["Western Conference"]
    del w_df["Western Conference"]
    dfs.append(w_df)
teams = pd.concat(dfs)

In [32]:
teams.tail()

     W   L  W/L%    GB   PS/G   PA/G    SRS  Year                  Team
13  42  30  .583     â€”  112.4  110.2   2.26  2021     Dallas Mavericks*
14  38  34  .528   4.0  113.3  112.3   1.07  2021    Memphis Grizzlies*
15  33  39  .458   9.0  111.1  112.8  -1.58  2021     San Antonio Spurs
16  31  41  .431  11.0  114.6  114.9  -0.20  2021  New Orleans Pelicans
17  17  55  .236  25.0  108.8  116.7  -7.50  2021       Houston Rockets

In [33]:
teams.to_csv("teams.csv")